ui:
  test: http://132.138.7.112:8080/index.php/system/Public/login.html
  prourl:
  preurl:
api:
  test: http://127.0.0.1:5000/api/huace/
  prourl:
  preurl:

runAPI:   #代表用例的编号 ，
runAPIS: [5,3,1]   #批量用例的编写,一个场景的用例

browser:
    type: chrome  #ie firefox chrome
    env: localhost  #headless #selenium_grid #docker

apidatabase:
    username: root
    password: root123
    dbname: airport_new
    serve: 132.138.7.138

webdatabase:
    username: root
    password: 123456
    dbname: pbapp
    serve: 132.138.7.112

appdata:
    devicesname: f0bc0371
    appname: com.atnc.vfr


email:




